### ISSUE TITLE
support python?

### ISSUE THREAD

**Issue by guuboi** [RaymondKirk/pico_zense_camera#1]

**Comment by RaymondCM** [comment]
The main driver is implemented in CPP but you can certainly use the camera in python! Just run it `roslaunch pico_zense_camera pz_camera.launch` after installing into your workspace and then use it in python like any other ROS image topic (example tutorial [here](http://wiki.ros.org/cv_bridge/Tutorials/ConvertingBetweenROSImagesAndOpenCVImagesPython)).
