### ISSUE TITLE
Rviz show image with RGB8

### ISSUE THREAD

**Issue by MikoyChinese** [RaymondKirk/pico_zense_camera#5]
https://github.com/RaymondKirk/pico_zense_camera/blob/52e69d87b5d4537bb0d3ba93c0d3c2ff9dd1f595/src/pico_zense_camera/pico_zense_manager.cpp#L251

If you want to show image in rviz, you need to change the `sensor_msgs::image_encodings::TYPE_8UC3` to `sensor_msgs::image_encodings::RGB8`.

**Comment by MikoyChinese** [comment]
It's my fault. That's OK.

**Comment by RaymondCM** [comment]
sensor_msgs::image_encodings::TYPE_8UC3 to sensor_msgs::image_encodings::RGB8 is the same, hope you fixed it.
