### ISSUE TITLE
Support for IMU data

### ISSUE THREAD

**Issue by mikkeljakobsen** [RaymondKirk/pico_zense_camera#6]
Hi,
Thanks for this great work. The camera has an IMU on board as well, which is accessible through the PsGetImu call. Are you planning to include support for the raw IMU data as well? If not, maybe you can guide me how I could implement this myself? 
Best regards, Mikkel

**Comment by RaymondCM** [comment]
Hello @mikkeljakobsen, I've now added it to this package. The IMU data is published on "pico_zense/imu", closing as this fixes the issue!
